/* =============================================================
   WEBSITE CONTENT DATA
   -------------------------------------------------------------
   This is the only file you need to edit to change the website
   content (profile, design work, films, and socials).
   ============================================================= */

const siteData = {
  /* --------------------------------------------------------- */
  /* PROFILE & IDENTITY                                        */
  /* --------------------------------------------------------- */
  profile: {
    name: "Patt",
    about:
      "Hi! I'm a designer who believes good design is felt, not just seen. Day to day I explore typography, color, and composition. Outside of design, I love watching films and pouring my thoughts into writing on Medium.",
    location: "Indonesia",
    email: "failnauqht@gmail.com",
    avatar: "assets/img/profile-patt.webp", // e.g. "assets/img/profile.jpg"
    logo: "assets/img/Failnauqht_Outline_wide.png", // navbar wordmark on sub-pages
  },

  /* --------------------------------------------------------- */
  /* STATS (shown in About)                                    */
  /* --------------------------------------------------------- */
  stats: [
    { label: "Years of Experience", value: 4 },
    { label: "Projects Completed", value: 32 },
  ],

  /* --------------------------------------------------------- */
  /* SKILLS                                                    */
  /* --------------------------------------------------------- */
  skills: [
    "Brand Identity",
    "UI / UX Design",
    "Illustration",
    "Typography",
    "Motion Graphics",
    "Photoshop",
    "Illustrator",
    "Figma",
  ],

  /* --------------------------------------------------------- */
  /* WORK — ALBUM / GALLERY                                    */
  /* This is a masonry album. To add a single piece, drop your */
  /* image into assets/img/ and add an entry below:            */
  /*                                                           */
  /*   { image: "assets/img/my-artwork.jpg" },                 */
  /*                                                           */
  /* To add a COLLECTION (one tile that opens into many images */
  /* — Foriio style), use an `images` array instead:           */
  /*                                                           */
  /*   {                                                       */
  /*     album: "My Series",                                   */
  /*     category: "Posters",                                  */
  /*     description: "A short intro for the collection.",     */
  /*     cover: "assets/img/series/01.jpg", // optional        */
  /*     images: [                                             */
  /*       "assets/img/series/01.jpg",                         */
  /*       "assets/img/series/02.jpg",                         */
  /*     ],                                                     */
  /*   },                                                      */
  /*                                                           */
  /* The layout AND each preview auto-adjust to the image's    */
  /* real resolution / aspect ratio (no cropping). Click a     */
  /* single image to open it full-size; click a collection to  */
  /* open the album, then click any image inside it.           */
  /*                                                           */
  /* Optional fields:                                          */
  /*   title    -> caption shown on hover                      */
  /*   category -> enables the filter bar (if 2+ categories)   */
  /*   ratio    -> ONLY used for empty placeholders below      */
  /* --------------------------------------------------------- */
  projects: [
    {
      album: "E-Sport Posters",
      role: "Design",
      cover: "assets/img/esport-posters/esport-posters-01.webp",
      images: [
        "assets/img/esport-posters/esport-posters-01.webp",
        "assets/img/esport-posters/esport-posters-02.webp",
        "assets/img/esport-posters/esport-posters-03.webp",
        "assets/img/esport-posters/esport-posters-04.webp",
        "assets/img/esport-posters/esport-posters-05.webp",
      ],
    },
    {
      album: "Futbol!",
      role: "Design",
      cover: "assets/img/futbol/futbol-01.webp",
      images: [
        "assets/img/futbol/futbol-01.webp",
        "assets/img/futbol/futbol-02.webp",
      ],
    },
    {
      album: "F1/F2/F3 DRIVERS",
      role: "Design",
      cover: "assets/img/f1/f1-01.webp",
      images: [
        "assets/img/f1/f1-01.webp",
        "assets/img/f1/f1-02.webp",
        "assets/img/f1/f1-03.webp",
        "assets/img/f1/f1-04.webp",
        "assets/img/f1/f1-05.webp",
        "assets/img/f1/f1-06.webp",
        "assets/img/f1/f1-07.webp",
        "assets/img/f1/f1-08.webp",
        "assets/img/f1/f1-09.webp",
        "assets/img/f1/f1-10.webp",
        "assets/img/f1/f1-11.webp",
        "assets/img/f1/f1-12.webp",
        "assets/img/f1/f1-13.webp",
        "assets/img/f1/f1-14.webp",
        "assets/img/f1/f1-15.webp",
        "assets/img/f1/f1-16.webp",
        "assets/img/f1/f1-17.webp",
      ],
    },
    {
      album: "Infographics",
      role: "Design",
      cover: "assets/img/infographics/infographics-01.webp",
      images: [
        "assets/img/infographics/infographics-01.webp",
        "assets/img/infographics/infographics-02.webp",
        "assets/img/infographics/infographics-03.webp",
      ],
    },
    {
      album: "Stress Capital Social-Media Works",
      role: "Design",
      cover: "assets/img/stress-capital/stress-capital-01.webp",
      images: [
        "assets/img/stress-capital/stress-capital-01.webp",
        "assets/img/stress-capital/stress-capital-02.webp",
        "assets/img/stress-capital/stress-capital-03.webp",
        "assets/img/stress-capital/stress-capital-04.webp",
        "assets/img/stress-capital/stress-capital-05.webp",
        "assets/img/stress-capital/stress-capital-06.webp",
        "assets/img/stress-capital/stress-capital-07.webp",
        "assets/img/stress-capital/stress-capital-08.webp",
      ],
    },
    {
      album: "Designs",
      role: "Design",
      cover: "assets/img/designs/designs-01.webp",
      images: [
        "assets/img/designs/designs-01.webp",
        "assets/img/designs/designs-02.webp",
        "assets/img/designs/designs-03.webp",
        "assets/img/designs/designs-04.webp",
        "assets/img/designs/designs-05.webp",
        "assets/img/designs/designs-06.webp",
        "assets/img/designs/designs-07.webp",
        "assets/img/designs/designs-08.webp",
        "assets/img/designs/designs-09.webp",
        "assets/img/designs/designs-10.webp",
        "assets/img/designs/designs-11.webp",
        "assets/img/designs/designs-12.webp",
      ],
    },
  ],

  /* --------------------------------------------------------- */
  /* FILMS WATCHED                                             */
  /* Format: "Title (rating/5)" or "Title (N/R)" if not rated. */
  /* To add a film, just paste a new line in this format.      */
  /* The list order = "recently watched" (newest first).       */
  /* Only titles are shown; ratings are used for sort/tooltip. */
  /* --------------------------------------------------------- */
  films: [
    "Half Man (N/R)",
    "Project Hail Mary (4.5/5)",
    "Wicked: For Good (3/5)",
    "Now You See Me: Now You Don't (3/5)",
    "Marty Supreme (3.5/5)",
    "The Long Walk (3/5)",
    "I Swear (4.5/5)",
    "Nuremberg (3.5/5)",
    "Eternity (3/5)",
    "Obsession (4.5/5)",
    "Wake Up Dead Man (3.5/5)",
    "The Voice of Hind Rajab (4/5)",
    "Frankenstein (4/5)",
    "Hamnet (4.5/5)",
    "Better Off Dead (4/5)",
    "My Oxford Year (1/5)",
    "The Fantastic 4: First Steps (3/5)",
    "Sore: A Wife from the Future (3.5/5)",
    "Materialists (3/5)",
    "Sentimental Value (3.5/5)",
    "Homebound (4/5)",
    "It Was Just an Accident (3.5/5)",
    "Pillion (2/5)",
    "Magellan (3/5)",
    "Kokuho (4/5)",
    "Urchin (3/5)",
    "Final Destination Bloodlines (3.5/5)",
    "Thunderbolts* (3/5)",
    "A Minecraft Movie (3/5)",
    "The Life List (2.5/5)",
    "Adolescence (4.5/5)",
    "When Life Gives You Tangerines (4.5/5)",
    "Sorry, Baby (3/5)",
    "Together (2/5)",
    "Train Dreams (3.5/5)",
    "Plainclothes (4/5)",
    "Twinless (3.5/5)",
    "Nosferatu (2.5/5)",
    "Wicked (3.5/5)",
    "Home Sweet Loan (3.5/5)",
    "On Swift Horses (3.5/5)",
    "We Live in Time (3.5/5)",
    "Queer (3.5/5)",
    "Lilies Not for Me (2.5/5)",
    "Deadpool & Wolverine (3.5/5)",
    "Inside Out 2 (3/5)",
    "The Count of Monte Cristo (4/5)",
    "Anora (4/5)",
    "The Substance (3/5)",
    "Before We Forget (4/5)",
    "Challengers (4/5)",
    "Damsel (2/5)",
    "18x2 Beyond Youthful Days (3.5/5)",
    "Upgraded (2/5)",
    "A Real Pain (4/5)",
    "Mentalese Express (3.5/5)",
    "Anyone But You (3/5)",
    "Falling in Love Like in Movies (4.5/5)",
    "The Marvels (1/5)",
    "The Hunger Games: The Ballad of Songbirds & Snakes (3.5/5)",
    "All the Light We Cannot See (3.5/5)",
    "Nuovo Olimpo (3/5)",
    "Godzilla Minus One (3.5/5)",
    "The Other Zoey (1.5/5)",
    "Society of the Snow (4/5)",
    "Dormitory (4/5)",
    "Poor Things (3/5)",
    "All of Us Strangers (4/5)",
    "The Holdovers (3/5)",
    "Saltburn (4/5)",
    "Oppenheimer (4/5)",
    "Barbie (2.5/5)",
    "No Hard Feelings (2.5/5)",
    "Spider-Man: Across the Spider-Verse (3.5/5)",
    "Fairlane (2.5/5)",
    "Asteroid City (4/5)",
    "The Zone of Interest (3.5/5)",
    "Strange Way of Life (3/5)",
    "Monster (4/5)",
    "Queen Charlotte: A Bridgerton Story (3.5/5)",
    "Guardians of the Galaxy Vol. 3 (4/5)",
    "Fireworks (4.5/5)",
    "Shazam! Fury of the Gods (2.5/5)",
    "Fireworks (3/5)",
    "Past Lives (4/5)",
    "A Man Called Otto (3.5/5)",
    "The Pale Blue Eye (2.5/5)",
    "Babylon (4.5/5)",
    "Avatar: The Way of Water (3/5)",
    "From Scratch (3.5/5)",
    "All Quiet on the Western Front (4.5/5)",
    "The Fabelmans (4.5/5)",
    "The Menu (3/5)",
    "Glass Onion (3.5/5)",
    "The Banshees of Inisherin (3.5/5)",
    "The Whale (4/5)",
    "The Gray Man (2.5/5)",
    "Minions: The Rise of Gru (3/5)",
    "Thor: Love and Thunder (1.5/5)",
    "Ms. Marvel (3/5)",
    "Missing Home (4/5)",
    "Close (4/5)",
    "Elvis (4/5)",
    "Triangle of Sadness (3.5/5)",
    "Aftersun (4.5/5)",
    "Top Gun: Maverick (4/5)",
    "Doctor Strange in the Multiverse of Madness (2.5/5)",
    "Gara-Gara Warisan (3/5)",
    "KKN: Curse of the Dancing Village (1/5)",
    "Heirs to the Land (3.5/5)",
    "Moon Knight (3.5/5)",
    "The Northman (3.5/5)",
    "Everything Everywhere All at Once (5/5)",
    "The Last 10 Years (2.5/5)",
    "The Adam Project (3/5)",
    "The Batman (3.5/5)",
    "Sublime (2.5/5)",
    "Badhaai Do (4.5/5)",
    "Uncharted (3/5)",
    "Against the Ice (3/5)",
    "Cha Cha Real Smooth (4/5)",
    "Spider-Man: No Way Home (3.5/5)",
    "Don't Look Up (3.5/5)",
    "West Side Story (3/5)",
    "tick, tick... BOOM! (4/5)",
    "Red Notice (2.5/5)",
    "Eternals (3.5/5)",
    "Encanto (3.5/5)",
    "Photocopier (3.5/5)",
    "Dear Evan Hansen (1/5)",
    "Last Night in Soho (3.5/5)",
    "Dune (3.5/5)",
    "The Hand of God (3.5/5)",
    "The Power of the Dog (4/5)",
    "Operation Hyacinth (2.5/5)",
    "Shang-Chi and the Legend of the Ten Rings (3/5)",
    "Free Guy (2.5/5)",
    "The French Dispatch of the Liberty, Kansas Evening Sun (3/5)",
    "The Medium (4/5)",
    "Great Freedom (4/5)",
    "The House of Flowers: The Movie (3/5)",
    "Loki (4/5)",
    "Cruella (3.5/5)",
    "Fate/Grand Order the Movie: Divine Realm of the Round Table: Camelot 2 Paladin; Agateram (3.5/5)",
    "My Blood and Bones in a Flowing Galaxy (4/5)",
    "Firebird (2.5/5)",
    "Brave: Gunjyou Senki (2.5/5)",
    "The Man with the Answers (3.5/5)",
    "The Map of Tiny Perfect Things (3.5/5)",
    "CODA (4.5/5)",
    "WandaVision (3.5/5)",
    "The Promised Neverland (3/5)",
    "Fate/Grand Order the Movie: Divine Realm of the Round Table: Camelot 1 Wandering; Agateram (3/5)",
    "Story of Kale: When Someone's in Love (3/5)",
    "Your Eyes Tell (3/5)",
    "Someone Has to Die (3/5)",
    "Clouds (3.5/5)",
    "Enola Holmes (3.5/5)",
    "The Devil All the Time (3/5)",
    "The Confidence Man JP – Episode of the Princess – (3.5/5)",
    "Theatre: A Love Story (3/5)",
    "Summer of 85 (2.5/5)",
    "Normal People (4/5)",
    "Your Name Engraved Herein (4.5/5)",
    "Our 30-Minute Sessions (4/5)",
    "One Day We'll Talk About Today (3.5/5)",
    "Habibie & Ainun 3 (3/5)",
    "Little Women (4/5)",
    "1917 (3/5)",
    "Last Christmas (2.5/5)",
    "Fate/Grand Order Absolute Demonic Front: Babylonia (N/R)",
    "Jojo Rabbit (4/5)",
    "Knives Out (4/5)",
    "The King (3.5/5)",
    "Joker (4/5)",
    "Ford v Ferrari (4/5)",
    "An Officer and a Spy (4/5)",
    "The Earth of Mankind (3/5)",
    "Spider-Man: Far From Home (3.5/5)",
    "Midsommar (3.5/5)",
    "Dark Phoenix (2/5)",
    "Ghost Writer (2.5/5)",
    "Little Love Song (2.5/5)",
    "Matthias & Maxime (4/5)",
    "Once Upon a Time... in Hollywood (3/5)",
    "Parasite (5/5)",
    "And Then We Danced (2.5/5)",
    "Aladdin (3/5)",
    "Avengers: Endgame (3.5/5)",
    "Shazam! (3.5/5)",
    "Five Feet Apart (3/5)",
    "Captain Marvel (2.5/5)",
    "12 Suicidal Teens (2/5)",
    "The Antique (3/5)",
    "Hotel Mumbai (3/5)",
    "Boy Erased (2.5/5)",
    "A Star Is Born (3.5/5)",
    "Roma (3/5)",
    "To All the Boys I've Loved Before (2.5/5)",
    "Crazy Rich Asians (3/5)",
    "Ant-Man and the Wasp (2.5/5)",
    "Shoplifters (4.5/5)",
    "Sauvage (2/5)",
    "Avengers: Infinity War (3.5/5)",
    "Dear Ex (3.5/5)",
    "Kids on the Slope (3/5)",
    "1985 (4/5)",
    "Love, Simon (3/5)",
    "Color Me True (3.5/5)",
    "Hereditary (3.5/5)",
    "Maze Runner: The Death Cure (3.5/5)",
    "The Greatest Showman (3.5/5)",
    "Coco (4/5)",
    "Tremble All You Want (3.5/5)",
    "Thor: Ragnarok (4/5)",
    "The Miracles of the Namiya General Store (2.5/5)",
    "Kingsman: The Golden Circle (3/5)",
    "Marrowbone (3.5/5)",
    "Breathe (3.5/5)",
    "Stronger (3/5)",
    "Lady Bird (3/5)",
    "Let Me Eat Your Pancreas (3.5/5)",
    "Dunkirk (3/5)",
    "Spider-Man: Homecoming (2.5/5)",
    "Bad Genius (4/5)",
    "Guardians of the Galaxy Vol. 2 (3/5)",
    "Life (3/5)",
    "God's Own Country (4/5)",
    "Call Me by Your Name (4.5/5)",
    "My Tomorrow, Your Yesterday (3.5/5)",
    "Doctor Strange (3/5)",
    "Miss Peregrine's Home for Peculiar Children (2.5/5)",
    "A Silent Voice: The Movie (3.5/5)",
    "Hacksaw Ridge (3/5)",
    "Arrival (3/5)",
    "La La Land (4.5/5)",
    "Brass Dreams (4/5)",
    "Your Name. (4.5/5)",
    "Looking: The Movie (3/5)",
    "Destruction Babies (2/5)",
    "Me Before You (3/5)",
    "If Cats Disappeared from the World (3/5)",
    "Train to Busan (3.5/5)",
    "X-Men: Apocalypse (2.5/5)",
    "Fair Haven (3/5)",
    "Captain America: Civil War (3.5/5)",
    "The Fundamentals of Caring (3.5/5)",
    "Sing Street (3/5)",
    "Manchester by the Sea (5/5)",
    "The Hunger Games: Mockingjay – Part 2 (3/5)",
    "Reply 1988 (4/5)",
    "The Man Who Knew Infinity (3/5)",
    "The Martian (4/5)",
    "Maze Runner: The Scorch Trials (2.5/5)",
    "Inside Out (3/5)",
    "Our Little Sister (4/5)",
    "The Age of Adaline (3.5/5)",
    "Avengers: Age of Ultron (2.5/5)",
    "Forget Me Not (2.5/5)",
    "Kingsman: The Secret Service (3/5)",
    "Blue Spring Ride (3/5)",
    "Unbroken (3/5)",
    "The Hunger Games: Mockingjay – Part 1 (3/5)",
    "Interstellar (5/5)",
    "As the Gods Will (2/5)",
    "Fury (3/5)",
    "Gone Girl (4/5)",
    "The Maze Runner (3.5/5)",
    "The Theory of Everything (3/5)",
    "Stand by Me Doraemon (4/5)",
    "Guardians of the Galaxy (3/5)",
    "Maleficent (3.5/5)",
    "Pride (3.5/5)",
    "Mommy (4/5)",
    "The Fault in Our Stars (2.5/5)",
    "X-Men: Days of Future Past (4/5)",
    "The Last: Naruto the Movie (4/5)",
    "Captain America: The Winter Soldier (4/5)",
    "The Grand Budapest Hotel (4/5)",
    "Boyhood (3/5)",
    "Whiplash (4/5)",
    "Boys (2.5/5)",
    "The Hunger Games: Catching Fire (3.5/5)",
    "Tom at the Farm (3.5/5)",
    "Prisoners (4/5)",
    "Enoshima Prism (4/5)",
    "About Time (4/5)",
    "Something in the Way (2.5/5)",
    "Before Midnight (3.5/5)",
    "The Kings of Summer (3.5/5)",
    "Kill Your Darlings (3/5)",
    "Les Misérables (3.5/5)",
    "Wreck-It Ralph (3.5/5)",
    "Out in the Dark (3.5/5)",
    "The Perks of Being a Wallflower (4/5)",
    "Frances Ha (N/R)",
    "Ted (2/5)",
    "The Avengers (3/5)",
    "The Hunger Games (3/5)",
    "Shame (3/5)",
    "You Are the Apple of My Eye (4/5)",
    "The Help (3.5/5)",
    "Captain America: The First Avenger (3.5/5)",
    "Drive (2.5/5)",
    "Oslo, August 31st (3/5)",
    "Detachment (3.5/5)",
    "Weekend (3.5/5)",
    "One Day (3.5/5)",
    "A Separation (4/5)",
    "The Social Network (3/5)",
    "Scott Pilgrim vs. the World (3.5/5)",
    "Inception (3.5/5)",
    "The Pacific (4/5)",
    "Shutter Island (4/5)",
    "Blue Valentine (3/5)",
    "Fantastic Mr. Fox (3.5/5)",
    "2012 (2/5)",
    "Cloudy with a Chance of Meatballs (3.5/5)",
    "Stolz der Nation (N/R)",
    "Inglourious Basterds (3.5/5)",
    "I Killed My Mother (4.5/5)",
    "Up (4/5)",
    "Knowing (3/5)",
    "(500) Days of Summer (3.5/5)",
    "The Dark Knight (4/5)",
    "WALL·E (4/5)",
    "Elizabeth: The Golden Age (3/5)",
    "Ratatouille (3.5/5)",
    "Love Songs (3.5/5)",
    "Atonement (3.5/5)",
    "The Prestige (4/5)",
    "The Devil Wears Prada (3.5/5)",
    "Like Minds (3/5)",
    "Cars (3.5/5)",
    "Little Miss Sunshine (4/5)",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe (3.5/5)",
    "Pride & Prejudice (4/5)",
    "Brokeback Mountain (4/5)",
    "Kingdom of Heaven (4/5)",
    "Mysterious Skin (4/5)",
    "Nobody Knows (4.5/5)",
    "Eternal Sunshine of the Spotless Mind (4/5)",
    "Before Sunset (3.5/5)",
    "The Motorcycle Diaries (4/5)",
    "The Lord of the Rings: The Return of the King (4/5)",
    "The Dreamers (4/5)",
    "Finding Nemo (3.5/5)",
    "The Lord of the Rings: The Two Towers (3/5)",
    "The Pianist (4/5)",
    "The Lord of the Rings: The Fellowship of the Ring (3.5/5)",
    "Band of Brothers (5/5)",
    "Y Tu Mamá También (3.5/5)",
    "Memento (3.5/5)",
    "X-Men (3/5)",
    "Requiem for a Dream (4/5)",
    "Burnt Money (3.5/5)",
    "Gladiator (4.5/5)",
    "Final Destination (3/5)",
    "American Psycho (3/5)",
    "The Talented Mr. Ripley (4/5)",
    "Fight Club (4/5)",
    "10 Things I Hate About You (3.5/5)",
    "October Sky (4/5)",
    "Shakespeare in Love (3/5)",
    "Saving Private Ryan (5/5)",
    "The Truman Show (3.5/5)",
    "Good Will Hunting (4/5)",
    "Titanic (3.5/5)",
    "La Haine (4/5)",
    "Before Sunrise (5/5)",
    "Little Women (4/5)",
    "Priest (3.5/5)",
    "Chungking Express (3.5/5)",
    "Forrest Gump (4/5)",
    "The Lion King (4.5/5)",
    "Schindler's List (4/5)",
    "The Living End (3.5/5)",
    "My Own Private Idaho (3/5)",
    "Awakenings (4/5)",
    "Home Alone (3.5/5)",
    "Close-Up (4.5/5)",
    "Dead Poets Society (4/5)",
    "Cinema Paradiso (5/5)",
    "Grave of the Fireflies (4.5/5)",
    "Maurice (3/5)",
    "Stand by Me (3.5/5)",
    "Ferris Bueller's Day Off (4/5)",
    "Top Gun (3/5)",
    "Another Country (3/5)",
    "Taxi Driver (3.5/5)",
    "The Godfather Part II (4/5)",
    "The Godfather (4.5/5)",
    "The Boy and the Wind (3.5/5)",
    "Purple Noon (3.5/5)",
  ],

  /* --------------------------------------------------------- */
  /* SOCIAL MEDIA / CONTACT LINKS                              */
  /* Single source of truth: the homepage dock AND the contact */
  /* page are both generated from this array.                  */
  /*                                                           */
  /*   short -> 1–2 letter fallback label (used if no icon)    */
  /*   icon  -> either a built-in name (see ICONS in main.js:  */
  /*            behance / instagram / foriio / medium /        */
  /*            letterboxd) OR a path to your own file, e.g.   */
  /*            "assets/img/icons/behance.svg"                 */
  /* --------------------------------------------------------- */
  socials: [
    {
      name: "Behance",
      short: "Be",
      icon: "behance",
      url: "https://www.behance.net/alfathrurut",
    },
    {
      name: "Instagram",
      short: "Ig",
      icon: "instagram",
      url: "https://instagram.com/failnauqht",
    },
    {
      name: "Foriio",
      short: "Fo",
      icon: "foriio",
      url: "https://foriio.com/failnauqht",
    },
    {
      name: "Medium",
      short: "M",
      icon: "medium",
      url: "https://medium.com/@xpatte",
    },
    {
      name: "Letterboxd",
      short: "Lb",
      icon: "letterboxd",
      url: "https://letterboxd.com/thispatt_",
    },
  ],
};
